### ISSUE TITLE
docker image build failed

### ISSUE THREAD

**Issue by fang19911030** [eth-sri/ilf#19]
I try to build the docker image, however I failed due to the docker keep complaining there is module pip3. Can anyone help?

**Comment by LostBenjamin** [comment]
Hi,

Thanks for your interest in ilf. We have fixed the issues and now the docker image can be successfully built on my local machine. Please try and let me know if there is any other issues.

Best,
Jingxuan

**Comment by fang19911030** [comment]
Thank you. I successfully build the docker. However,  from the Usage section in README, I still not sure about how to run ilf in docker. Could you give an an example command about how to use docker execute the ilf. Thank you.

**Comment by LostBenjamin** [comment]
We just added one line to the dockerfile. Please update.

After buliding the docker, you can try:
```
docker run -it ilf
python3 -m ilf --proj ./example/crowdsale/ --contract Crowdsale --fuzzer imitation --model ./model/ --limit 2000
```

**Comment by fang19911030** [comment]
Sorry, this command does not work. The docker throws error:  /usr/bin/python3: No module named ilf, could you have a look?

**Comment by LostBenjamin** [comment]
The command works for me. As I said, we added one line to the dockerfile. Did you rebuild the docker?

**Comment by fang19911030** [comment]
Yes, I clone the whole repo once again.  I still have the same issue.

**Comment by LostBenjamin** [comment]
Did you rebuild the docker by running `docker build -t ilf .`?

Cloning the repo does not mean rebuilding the docker.

**Comment by fang19911030** [comment]
Yes, I did.  I don't know why it still does not work. Luckily, I install all the things manually and it works. But I still have to manually install some python packages.

**Comment by LostBenjamin** [comment]
Glad to hear that you made it work! Let me know in case of any other problems.

I will close this issue now.
